INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (0, 'klmlboom','1234','이현승','klmlboom@naver.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'klml1013','1234','이시언','google@naver.com');
INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, COUNT_ANSWER) VALUES (2, 0, '테스트질문입니다.','별내용없는 테스트 내용 입니다.', CURRENT_TIMESTAMP(), 0);